-- MySQL Script generated by MySQL Workbench
-- Fri May 22 23:33:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema epl_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epl_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epl_db` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Managers` (
  `Manager` VARCHAR(255) NOT NULL,
  `Nationality` VARCHAR(255) NOT NULL,
  `Status` VARCHAR(255) NOT NULL,
  `Team` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Manager`));


-- -----------------------------------------------------
-- Table `mydb`.`Stadiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stadiums` (
  `Team` VARCHAR(255) NOT NULL,
  `Venue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Team`));


-- -----------------------------------------------------
-- Table `mydb`.`Matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matches` (
  `Match_Num` INT NOT NULL,
  `Match_Day` INT NULL,
  `Date` DATE NOT NULL,
  `Half time score Team_1` INT NULL,
  `Half time score Team_2` INT NULL,
  `Full time score Team_1` INT NOT NULL,
  `Full time score Team_2` INT NOT NULL,
  `Team_1` VARCHAR(225) NOT NULL,
  `Team_2` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Match_Num`));

USE `epl_db` ;

-- -----------------------------------------------------
-- Table `epl_db`.`stadiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epl_db`.`stadiums` (
  `Team` VARCHAR(255) NOT NULL,
  `Venue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Team`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `epl_db`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epl_db`.`managers` (
  `Manager` VARCHAR(255) NOT NULL,
  `Nationality` VARCHAR(255) NOT NULL,
  `Status` VARCHAR(255) NOT NULL,
  `Team` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Manager`),
  INDEX `fk_managers_stadiums_idx` (`Team` ASC) VISIBLE,
  CONSTRAINT `fk_managers_stadiums`
    FOREIGN KEY (`Team`)
    REFERENCES `epl_db`.`stadiums` (`Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `epl_db`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epl_db`.`matches` (
  `Match_Num` INT NOT NULL,
  `Match_Day` INT NULL DEFAULT NULL,
  `Date` DATE NOT NULL,
  `Half time score Team_1` INT NULL DEFAULT NULL,
  `Half time score Team_2` INT NULL DEFAULT NULL,
  `Full time score Team_1` INT NOT NULL,
  `Full time score Team_2` INT NOT NULL,
  `Team_1` VARCHAR(225) NOT NULL,
  `Team_2` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Match_Num`),
  INDEX `fk_matches_stadiums1_idx` (`Team_1` ASC) VISIBLE,
  INDEX `fk_matches_stadiums2_idx` (`Team_2` ASC) VISIBLE,
  CONSTRAINT `fk_matches_stadiums1`
    FOREIGN KEY (`Team_1`)
    REFERENCES `epl_db`.`stadiums` (`Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_stadiums2`
    FOREIGN KEY (`Team_2`)
    REFERENCES `epl_db`.`stadiums` (`Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
